name: CosmoVISIO
theme: jekyll-theme-minimal
description: O nome “cosmoVISIO” reflete nossa visão abrangente e integrada do mundo.
Cosmo, do grego “kosmos”, significa “universo” ou “mundo”, e sugere um sistema complexo e interconectado. Visio, do latim, significa “visão”, indicando nossa capacidade de ver e imaginar o futuro. 
Juntos, eles formam “cosmovisão”, um termo que se refere à forma como enxergamos e interpretamos o mundo ao nosso redor.
Nossa cosmovisão é refletida em nossa proposta de promover o turismo ecológico em Pernambuco através da plataforma EcoPasseiosPE, respeitando tanto o meio ambiente quanto as comunidades locais, criando soluções que permitam aos usuários explorar a rica biodiversidade e cultura de Pernambuco de forma responsável e educativa, considerando a sustentabilidade ambiental, social e econômica.
